"""create users table

Revision ID: 0001
Revises:
Create Date: 2026-06-13

Hand-authored (not autogenerated) so it is deterministic and reviewed. Uses
``sa.Uuid`` (native UUID on Postgres, CHAR(32) on SQLite) and non-native enums
(VARCHAR + CHECK) so it applies cleanly on both dialects.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STATUS = sa.Enum(
    "PENDING_VERIFICATION",
    "ACTIVE",
    "LOCKED",
    "DEACTIVATED",
    name="user_status",
    native_enum=False,
    length=32,
)
_ROLE = sa.Enum(
    "learner",
    "instructor",
    "admin",
    name="user_role",
    native_enum=False,
    length=16,
)


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("status", _STATUS, nullable=False, server_default="ACTIVE"),
        sa.Column("role", _ROLE, nullable=False, server_default="learner"),
        sa.Column("failed_attempts", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_version", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
